CREATE TABLE IF NOT EXISTS Usuario (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  endereco VARCHAR(255),
  provincia VARCHAR(255),
  telefone VARCHAR(255) NOT NULL UNIQUE,
  provincia VARCHAR(255),
  bi VARCHAR(255),
  areaAtuacao VARCHAR(255),
  bi VARCHAR(255),
  bi VARCHAR(255),
  role ENUM('Usuario', 'Empreendedor', 'Admin') NOT NULL
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Empresa (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL UNIQUE,
  nif VARCHAR(255) NOT NULL UNIQUE,
  proprietario_id INT UNIQUE,
  FOREIGN KEY (proprietario_id) REFERENCES Usuario(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

